### ISSUE TITLE
SecretServerClientError trying to access secret

### ISSUE THREAD

**Issue by GreyArea765** [thycotic/python-tss-sdk#43]
From your documentation, I put together the following code to authenticate and gain access to a secret:

```python
from thycotic.secrets.server import DomainPasswordGrantAuthorizer, SecretServer

authorizer = DomainPasswordGrantAuthorizer("https://my_url/SecretServer",
                                           "username",
                                           "domain",
                                           "password")

secret_server = SecretServer("https://my_url/SecretServer", authorizer)

# Set to the ID of a secret I pulled from its URL, which is the only place I can see which might indicate a Secret ID.
secret = secret_server.get_secret(100)
```

However I'm getting SecretServerClientError

```shell
Traceback (most recent call last):
  File "getsec.py", line 10, in <module>
    secret = secret_server.get_secret(1172)
  File "/home/user/.local/share/virtualenvs/secretservertest-ZaIMSpbY/lib/python3.8/site-packages/thycotic/secrets/server.py", line 333, in get_secret
    response = self.get_secret_json(id, query_params=query_params)
  File "/home/user/.local/share/virtualenvs/secretservertest-ZaIMSpbY/lib/python3.8/site-packages/thycotic/secrets/server.py", line 304, in get_secret_json
    return self.process(requests.get(endpoint_url, headers=self.headers())).text
  File "/home/user/.local/share/virtualenvs/secretservertest-ZaIMSpbY/lib/python3.8/site-packages/thycotic/secrets/server.py", line 266, in headers
    return self.authorizer.headers()
  File "/home/user/.local/share/virtualenvs/secretservertest-ZaIMSpbY/lib/python3.8/site-packages/thycotic/secrets/server.py", line 138, in headers
    self.get_access_token(), existing_headers
  File "/home/user/.local/share/virtualenvs/secretservertest-ZaIMSpbY/lib/python3.8/site-packages/thycotic/secrets/server.py", line 207, in get_access_token
    self._refresh()
  File "/home/user/.local/share/virtualenvs/secretservertest-ZaIMSpbY/lib/python3.8/site-packages/thycotic/secrets/server.py", line 193, in _refresh
    self.access_grant = self.get_access_grant(
  File "/home/user/.local/share/virtualenvs/secretservertest-ZaIMSpbY/lib/python3.8/site-packages/thycotic/secrets/server.py", line 173, in get_access_grant
    return json.loads(SecretServer.process(response).content)
  File "/home/user/.local/share/virtualenvs/secretservertest-ZaIMSpbY/lib/python3.8/site-packages/thycotic/secrets/server.py", line 260, in process
    raise SecretServerClientError(message, response)
thycotic.secrets.server.SecretServerClientError
```

**Comment by EndlessTrax** [comment]
A `SecretServerClientError` is returned when you get a non-200 response from SecretServer. That would suggest the account you used to authenticate to the secret doesn't have permission to read secret `1172`.

You can also check that you have a valid `access_grant` by inspecting your `SecretServer` object: `secret_server.authorizer.access_grant`

**Comment by GreyArea765** [comment]
That's interesting, the credentials I am using are my own and I definitely do have access to that secret.  You're right though,  `secret_server.authorizer` object only contains a `grant_request` object  by the time it hits `secret_server.get_secret`

**Comment by EndlessTrax** [comment]
Does your Secret Server instance have `webservices` enabled in the configuration?

Something else you could try is to create an app user, give it permission to read the secret, then try using the `PasswordGrantAuthorizer` to pull the secrets. If that works then that narrows down the problem.
